//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitTB
    {
        public UnitTB()
        {
            this.ProductTBs = new HashSet<ProductTB>();
        }
    
        public int Unit_ID { get; set; }
        public string Unit_Name { get; set; }
    
        public virtual ICollection<ProductTB> ProductTBs { get; set; }
    }
}
