//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJackAssignmentMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardPack
    {
        public int Card_No { get; set; }
        public string Card_Name { get; set; }
        public int Card_Value { get; set; }
    }
}
