//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTB
    {
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> Unit_Id { get; set; }
        public Nullable<float> Price { get; set; }
    
        public virtual CategoryTB CategoryTB { get; set; }
        public virtual UnitTB UnitTB { get; set; }
    }
}
